# Generated by Django 5.2.10 on 2026-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_distance_km',
            field=models.FloatField(default=0.0),
        ),
    ]
