# Generated by Django 5.2.10 on 2026-02-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_total_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='harsh_acceleration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='harsh_braking_count',
            field=models.IntegerField(default=0),
        ),
    ]
