# Generated by Django 5.2.10 on 2026-02-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_harsh_acceleration_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='crash_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='crash_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='crash_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
