# Generated by Django 5.2.10 on 2026-02-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_crash_detected_trip_crash_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivingevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivingevent',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
