# Generated by Django 5.2.10 on 2026-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_drivingevent_latitude_drivingevent_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='max_speed_over_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='speeding_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='speeding_violations_count',
            field=models.IntegerField(default=0),
        ),
    ]
