# Generated by Django 5.2.10 on 2026-03-26 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_max_speed_over_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpoint',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
